changelog:
  categories:
    - title: Безопасность
      labels: [security]
    - title: Новые возможности
      labels: [enhancement]
    - title: Исправления
      labels: [bug]
    - title: Прочие изменения
      labels: ['*']
