changelog:
  categories:
    - title: Безопасность
      labels: [безопасность]
    - title: Новые возможности
      labels: [улучшение]
    - title: Исправления
      labels: [ошибка]
    - title: Прочие изменения
      labels: ['*']
