<#
    gen_resources.ps1
    Single source of truth for embedded runtime resources.

    Scans <PayloadDir> (expects sub-folders bin\ and lists\) and emits:
      1. A Windows resource script (.rc) with one RCDATA entry per file.
      2. A C++ header describing every resource: RCDATA id, extract-relative
         path, logical name, byte size, lowercase SHA-256 and category.

    Because both outputs are produced from the same enumeration, the RCDATA
    ids in the .rc and the ids baked into the manifest header can never drift.

    Usage:
      powershell -NoProfile -ExecutionPolicy Bypass -File gen_resources.ps1 `
          -PayloadDir <dir> -RcOut <file.rc> -HeaderOut <file.h>
#>
[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)][string]$PayloadDir,
    [Parameter(Mandatory = $true)][string]$RcOut,
    [Parameter(Mandatory = $true)][string]$HeaderOut
)

$ErrorActionPreference = "Stop"

function Get-Category([string]$folder) {
    switch ($folder) {
        "bin"   { return 0 } # BINARY  - verified + re-extracted every launch, ACL locked
        "lists" { return 1 } # LIST    - data, extracted only when missing
        default { throw "Unknown payload sub-folder '$folder'" }
    }
}

$PayloadDir = (Resolve-Path $PayloadDir).Path
$rootItems = @(Get-ChildItem -LiteralPath $PayloadDir -Force)
foreach ($rootItem in $rootItems) {
    if (($rootItem.Attributes -band [IO.FileAttributes]::ReparsePoint) -ne 0) {
        throw "Reparse object is forbidden in embedded payload: $($rootItem.FullName)"
    }
    if (-not $rootItem.PSIsContainer -or $rootItem.Name -notin @('bin', 'lists')) {
        throw "Unexpected embedded payload root entry: $($rootItem.Name)"
    }
}

$items = @()
foreach ($folder in @("bin", "lists")) {
    $dir = Join-Path $PayloadDir $folder
    if (-not (Test-Path -LiteralPath $dir -PathType Container)) {
        throw "Required embedded payload directory is missing: $dir"
    }
    $children = @(Get-ChildItem -LiteralPath $dir -Force)
    foreach ($child in $children) {
        if ($child.PSIsContainer -or
            (($child.Attributes -band [IO.FileAttributes]::ReparsePoint) -ne 0)) {
            throw "Nested directory/reparse object is unsupported: $($child.FullName)"
        }
    }
    $children | Sort-Object Name | ForEach-Object {
        $bytes  = [System.IO.File]::ReadAllBytes($_.FullName)
        $sha    = (Get-FileHash -Algorithm SHA256 -LiteralPath $_.FullName).Hash.ToLowerInvariant()
        $items += [pscustomobject]@{
            Folder   = $folder
            Name     = $_.Name
            FullPath = $_.FullName
            Size     = $bytes.LongLength
            Sha256   = $sha
            Category = (Get-Category $folder)
            RelPath  = "$folder\$($_.Name)"
        }
    }
}

if ($items.Count -eq 0) { throw "No payload files found under $PayloadDir" }

# Assign stable ids: bin group first, then lists, sorted by name within group.
$id = 1000
foreach ($it in $items) { $id++; $it | Add-Member -NotePropertyName Id -NotePropertyValue $id }

# ---- Emit .rc ------------------------------------------------------------
$rc = New-Object System.Text.StringBuilder
[void]$rc.AppendLine("// AUTO-GENERATED by cmake/gen_resources.ps1 - DO NOT EDIT.")
[void]$rc.AppendLine("// RCDATA payload for CHEBURNET runtime extraction.")
[void]$rc.AppendLine("")
foreach ($it in $items) {
    $escaped = $it.FullPath.Replace("\", "\\")
    [void]$rc.AppendLine("$($it.Id) RCDATA ""$escaped""")
}
$rcDir = Split-Path -Parent $RcOut
if (-not (Test-Path $rcDir)) { New-Item -ItemType Directory -Force $rcDir | Out-Null }
[System.IO.File]::WriteAllText($RcOut, $rc.ToString(), (New-Object System.Text.UTF8Encoding($false)))

# ---- Emit header ---------------------------------------------------------
$h = New-Object System.Text.StringBuilder
[void]$h.AppendLine("// AUTO-GENERATED by cmake/gen_resources.ps1 - DO NOT EDIT.")
[void]$h.AppendLine("#pragma once")
[void]$h.AppendLine("#include <cstdint>")
[void]$h.AppendLine("")
[void]$h.AppendLine("namespace cheburnet {")
[void]$h.AppendLine("")
[void]$h.AppendLine("// Category of an embedded resource.")
[void]$h.AppendLine("enum class ResourceCategory : int {")
[void]$h.AppendLine("    Binary = 0, // engine binary: verified + re-extracted every launch, ACL locked")
[void]$h.AppendLine("    List   = 1, // immutable upstream data; user overlays live under user/lists")
[void]$h.AppendLine("};")
[void]$h.AppendLine("")
[void]$h.AppendLine("struct EmbeddedResource {")
[void]$h.AppendLine("    unsigned int      rcId;        // RCDATA numeric id (matches cheburnet payload .rc)")
[void]$h.AppendLine("    const wchar_t*    relPath;      // path under the versioned runtime dir")
[void]$h.AppendLine("    const char*       logicalName;  // stable file name")
[void]$h.AppendLine("    unsigned long long expectedSize;")
[void]$h.AppendLine("    const char*       sha256;       // lowercase hex")
[void]$h.AppendLine("    ResourceCategory  category;")
[void]$h.AppendLine("};")
[void]$h.AppendLine("")
[void]$h.AppendLine("inline constexpr EmbeddedResource kEmbeddedResources[] = {")
foreach ($it in $items) {
    $rel = $it.RelPath.Replace("\", "\\")
    $catName = if ($it.Category -eq 0) { "ResourceCategory::Binary" } else { "ResourceCategory::List" }
    [void]$h.AppendLine("    { $($it.Id)u, L""$rel"", ""$($it.Name)"", $($it.Size)ull, ""$($it.Sha256)"", $catName },")
}
[void]$h.AppendLine("};")
[void]$h.AppendLine("")
[void]$h.AppendLine("inline constexpr int kEmbeddedResourceCount =")
[void]$h.AppendLine("    static_cast<int>(sizeof(kEmbeddedResources) / sizeof(kEmbeddedResources[0]));")
[void]$h.AppendLine("")
[void]$h.AppendLine("} // namespace cheburnet")
$hDir = Split-Path -Parent $HeaderOut
if (-not (Test-Path $hDir)) { New-Item -ItemType Directory -Force $hDir | Out-Null }
[System.IO.File]::WriteAllText($HeaderOut, $h.ToString(), (New-Object System.Text.UTF8Encoding($false)))

Write-Output "gen_resources: $($items.Count) resources -> $RcOut, $HeaderOut"
foreach ($it in $items) { Write-Output ("  [{0}] {1,-38} {2,9} bytes  {3}" -f $it.Id, $it.RelPath, $it.Size, $it.Sha256.Substring(0,16)) }
