[CmdletBinding()]
param([Parameter(Mandatory = $true)][string]$PublicKey,
      [Parameter(Mandatory = $true)][string]$HeaderOut)
$ErrorActionPreference = 'Stop'
$document = Get-Content -LiteralPath $PublicKey -Raw -Encoding UTF8 | ConvertFrom-Json
$keys = @(if ($null -ne $document.keys) { @($document.keys) } else { $document })
if ($keys.Count -lt 1 -or $keys.Count -gt 4) { throw 'trusted update key count must be 1..4' }
$seen = @{}
foreach ($key in $keys) {
    if ($key.algorithm -ne 'ECDSA_P256_SHA256' -or $key.key_id -notmatch '^[a-z0-9-]{1,64}$' -or
        $seen.ContainsKey([string]$key.key_id)) { throw 'unsupported/duplicate update public key metadata' }
    $seen[[string]$key.key_id] = $true
    $x = [Convert]::FromBase64String($key.x)
    $y = [Convert]::FromBase64String($key.y)
    if ($x.Length -ne 32 -or $y.Length -ne 32) { throw 'P-256 coordinates must be 32 bytes' }
}
function Bytes([byte[]]$value) { return ($value | ForEach-Object { '0x{0:x2}' -f $_ }) -join ', ' }
$lines = @(
    '// AUTO-GENERATED by cmake/gen_update_keys.ps1 - DO NOT EDIT.',
    '#pragma once',
    'namespace cheburnet::update {',
    'struct TrustedUpdateKey { const char* keyId; unsigned char x[32]; unsigned char y[32]; };',
    'inline constexpr TrustedUpdateKey kTrustedUpdateKeys[] = {'
)
foreach ($key in $keys) {
    $x = [Convert]::FromBase64String($key.x)
    $y = [Convert]::FromBase64String($key.y)
    $lines += ('    {{ "{0}", {{ {1} }}, {{ {2} }} }},' -f $key.key_id,(Bytes $x),(Bytes $y))
}
$lines += @(
    '};',
    'inline constexpr int kTrustedUpdateKeyCount =',
    '    static_cast<int>(sizeof(kTrustedUpdateKeys) / sizeof(kTrustedUpdateKeys[0]));',
    '} // namespace cheburnet::update'
)
$parent = Split-Path -Parent $HeaderOut
if (-not (Test-Path $parent)) { New-Item -ItemType Directory -Path $parent -Force | Out-Null }
[IO.File]::WriteAllLines($HeaderOut, $lines, [Text.UTF8Encoding]::new($false))
Write-Output "gen_update_keys: embedded key_ids=$([string]::Join(',', @($keys.key_id)))"
