<#
    gen_mascot.ps1
    Turns resources/mascot/cheburashka.txt into a byte-exact C++ header
    (MascotFullArt.h). The '@' placeholder in the art marks the cap star and is
    replaced with U+2605 (BLACK STAR); ConsoleRenderer::DrawMascot then paints
    that glyph red while the rest is drawn green.
#>
[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)][string]$ArtFile,
    [Parameter(Mandatory = $true)][string]$HeaderOut
)
$ErrorActionPreference = "Stop"

$star = [char]0x2605
$lines = [System.IO.File]::ReadAllLines($ArtFile, [System.Text.Encoding]::UTF8)

# Drop trailing empty lines only.
$end = $lines.Length
while ($end -gt 0 -and [string]::IsNullOrWhiteSpace($lines[$end - 1])) { $end-- }
$lines = $lines[0..([Math]::Max($end - 1, 0))]

$starCount = 0
$maxWidth = 0
$out = @()
foreach ($ln in $lines) {
    $converted = $ln.Replace('@', $star)
    $starCount += ([regex]::Matches($converted, [regex]::Escape($star))).Count
    if ($converted.Length -gt $maxWidth) { $maxWidth = $converted.Length }
    $escaped = $converted.Replace('\', '\\').Replace('"', '\"')
    $out += "    L`"$escaped`","
}

if ($starCount -ne 1) {
    Write-Warning "gen_mascot: expected exactly one star marker, found $starCount"
}

$sb = New-Object System.Text.StringBuilder
[void]$sb.AppendLine("// AUTO-GENERATED by cmake/gen_mascot.ps1 from resources/mascot/cheburashka.txt")
[void]$sb.AppendLine("// DO NOT EDIT. Edit the .txt source and regenerate.")
[void]$sb.AppendLine("#pragma once")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("namespace cheburnet {")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("inline const wchar_t* const kMascotFullLines[] = {")
foreach ($l in $out) { [void]$sb.AppendLine($l) }
[void]$sb.AppendLine("};")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("inline constexpr int kMascotFullCount =")
[void]$sb.AppendLine("    static_cast<int>(sizeof(kMascotFullLines) / sizeof(kMascotFullLines[0]));")
[void]$sb.AppendLine("inline constexpr int kMascotFullWidth = $maxWidth;")
[void]$sb.AppendLine("inline constexpr wchar_t kMascotStar = static_cast<wchar_t>(0x2605);")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("} // namespace cheburnet")

$dir = Split-Path -Parent $HeaderOut
if (-not (Test-Path $dir)) { New-Item -ItemType Directory -Force $dir | Out-Null }
[System.IO.File]::WriteAllText($HeaderOut, $sb.ToString(), (New-Object System.Text.UTF8Encoding($false)))

Write-Output "gen_mascot: $($out.Count) lines, width=$maxWidth, stars=$starCount -> $HeaderOut"
