[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)][string]$Provenance,
    [Parameter(Mandatory = $true)][string]$HeaderOut
)
$ErrorActionPreference = 'Stop'
$raw = Get-Content -LiteralPath $Provenance -Raw -Encoding UTF8
$p = $raw | ConvertFrom-Json
foreach ($required in @('provider','version','tag','release_id','source_url','release_url',
                         'imported_at_utc','archive_sha256','upstream_commit','immutable')) {
    if ($null -eq $p.$required -or [string]::IsNullOrWhiteSpace([string]$p.$required)) {
        throw "provenance missing $required"
    }
}
if ($p.archive_sha256 -notmatch '^[a-f0-9]{64}$') { throw 'invalid archive_sha256' }
if ($p.upstream_commit -notmatch '^[a-f0-9]{40}$') { throw 'invalid upstream_commit' }
if ($p.immutable -ne $true) { throw 'upstream release must be immutable' }
if ($p.provider -cne 'Flowseal/zapret-discord-youtube') { throw 'unexpected provider' }
if ($p.version -notmatch '^[0-9]+(?:\.[0-9]+){1,7}[a-z]?$' -or $p.tag -cne $p.version) {
    throw 'invalid or mismatched version/tag'
}
if ([long]$p.release_id -le 0) { throw 'invalid release_id' }
foreach ($url in @([string]$p.source_url,[string]$p.release_url)) {
    if ($url -notmatch '^https://[^\s]+$') { throw 'provenance URL must be HTTPS' }
}
if ($p.imported_at_utc -notmatch '^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}Z$') {
    throw 'invalid imported_at_utc'
}
function Escape([string]$s) { return $s.Replace('\','\\').Replace('"','\"') }
$lines = @(
    '// AUTO-GENERATED by cmake/gen_provenance.ps1 - DO NOT EDIT.',
    '#pragma once',
    'namespace cheburnet::upstream {',
    ('inline constexpr wchar_t kProvider[] = L"{0}";' -f (Escape $p.provider)),
    ('inline constexpr wchar_t kVersion[] = L"{0}";' -f (Escape $p.version)),
    ('inline constexpr wchar_t kTag[] = L"{0}";' -f (Escape $p.tag)),
    ('inline constexpr unsigned long long kReleaseId = {0}ull;' -f $p.release_id),
    ('inline constexpr wchar_t kSourceUrl[] = L"{0}";' -f (Escape $p.source_url)),
    ('inline constexpr wchar_t kReleaseUrl[] = L"{0}";' -f (Escape $p.release_url)),
    ('inline constexpr wchar_t kImportedAt[] = L"{0}";' -f (Escape $p.imported_at_utc)),
    ('inline constexpr char kArchiveSha256[] = "{0}";' -f $p.archive_sha256),
    ('inline constexpr char kCommit[] = "{0}";' -f $p.upstream_commit),
    '} // namespace cheburnet::upstream'
)
$parent = Split-Path -Parent $HeaderOut
if (-not (Test-Path -LiteralPath $parent)) { New-Item -ItemType Directory -Force $parent | Out-Null }
[IO.File]::WriteAllLines($HeaderOut, $lines, [Text.UTF8Encoding]::new($false))
Write-Output "gen_provenance: $($p.provider) $($p.version), release $($p.release_id)"
