#include "Mascot.h"

#include "MascotFullArt.h" // generated from resources/mascot/cheburashka.txt

namespace cheburnet {
namespace {

// Full mascot: detailed Braille-art Cheburashka (two enormous round ears and a
// round face) with a red star above the head. Generated byte-exact from the
// .txt source; the star glyph (U+2605) is painted red by ConsoleRenderer while
// the rest is drawn green.
MascotArt BuildFull() {
    MascotArt a;
    a.lines.reserve(static_cast<size_t>(kMascotFullCount));
    for (int i = 0; i < kMascotFullCount; ++i) a.lines.emplace_back(kMascotFullLines[i]);
    a.starMarker = kMascotStar;
    a.width = kMascotFullWidth;
    // Eye "glint" cells (bright sparkle overlay) - safe, never distorts the art.
    a.glint = true;
    a.eyes = {{41, 9}, {52, 9}};
    return a;
}

// Compact mascot for narrow windows / limited fonts: plain ASCII with an L'★'.
// Eyes "o o" on row 5 blink open<->closed.
const MascotArt kCompactArt = {
    {
        L"    ___         ___    ",
        L"   /   \\  ___  /   \\   ",
        L"  |     |/ ★ \\|     |  ",
        L"   \\   /|___| \\   /    ",
        L"    \\_/ |   |  \\_/     ",
        L"        |o o|          ",
        L"        | ^ |          ",
        L"        |\\_/|          ",
        L"        |___|          ",
    },
    L'★',
    23,
    {{9, 5}, {11, 5}}, // eye cells
    true,              // blinkSwap
    false,             // glint
    L'o',
    L'-',
};

} // namespace

const MascotArt& MascotFull() {
    static const MascotArt art = BuildFull();
    return art;
}
const MascotArt& MascotCompact() { return kCompactArt; }

const MascotArt& MascotForWidth(int consoleWidth) {
    // Use the full Braille mascot when the window can hold it with a small margin.
    return consoleWidth >= (MascotFull().width + 6) ? MascotFull() : MascotCompact();
}

} // namespace cheburnet
